"use client";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import '../styles/globals.css'
import '../styles/components-st/card-pieces.css'
import '../styles/components-st/editor.css'
import store, { persistor } from "../store/index";
import DBContext from '../context/context'
import Header from '../components/header'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <PersistGate persistor={persistor}>
            <DBContext>
              {/* <Header /> */}
              {children}
            </DBContext>
          </PersistGate>
        </Provider>
      </body>
    </html>
  )
}
